### ISSUE TITLE
Simple example is panicing

### ISSUE THREAD

**Issue by gkampitakis** [adamluzsi/testcase#12]
Hey 👋  I am running the simple example from the docs and I get this error 

Example:

```go
func Test_withTestcaseSpec(t *testing.T) {
	s := testcase.NewSpec(t)

	s.Test("", func(tc *testcase.T) {
		tc.Must.True(true)
		_ = tc.Random.String()
	})
}
```

Error:

```sh
--- FAIL: Test_withTestcaseSpec (0.00s)
panic: testing: t.Run called during t.Cleanup [recovered]
	panic: testing: t.Run called during t.Cleanup
```

go version go1.20.4 darwin/arm64

**Comment by gkampitakis** [comment]
I was using and older version `v0.108.2` doesn't happen on `v0.133.0`

**Comment by adamluzsi** [comment]
Hello @gkampitakis,

I just realised that I missed your message – my sincerest apologies.

Firstly, thank you for your enquiry and feedback. There was a behaviour shift concerning `testing.TB.Cleanup`, which rendered the original design obsolete. I adjusted the underlying implementation promptly once I noticed the issue, maintaining complete backward compatibility. The only downside is that test shuffling won't occur at the top level anymore, but everything under a testing context should remain unaffected.

Please contact me here or on GopherSlack if you have more questions. The project has seen numerous new features since version v0.108.2.

Please spare the time to share your thoughts on your use of it and any feedback you might have. That would greatly benefit the project.

Cheers,
Adam
